### ISSUE TITLE
Can't find libctesseract even though it's installed

### ISSUE THREAD

**Issue by clintharris** [dsoprea/TightOCR#4]
I successfully built and installed ctesseract:

```
[ctesseract-1.0/build]$ sudo make install
[100%] Built target ctesseract
Install the project...
-- Install configuration: "Debug"
-- Installing: /usr/local/lib/libctesseract.so.1.0.1
-- Up-to-date: /usr/local/lib/libctesseract.so.1.0.0
-- Up-to-date: /usr/local/lib/libctesseract.so
```

However, when I try to install TightOCR it still can't find ctesseract:

```
[TightOCR-0.4.4]$ python ./setup.py install
running install
Checking for libctesseract.
The libctesseract shared-library could not be found/imported.
```

Any ideas as to why this might be happening?

**Comment by clintharris** [comment]
FYI, it looks like just loading the shared library by filename (in `library_ctess.py`) doesn't work...but specifying full path does:

``` python
$ python
Python 2.7.3 (default, Nov 22 2013, 15:43:29) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-3)] on linux2
Type "help", "copyright", "credits" or "license" for more information.

>>> from ctypes.util import find_library
>>> from ctypes import cdll
>>> fp = find_library('ctesseract')
>>> print fp
'libctesseract.so.1.0.0'

# Can't load library with just the filename...
>>> cdll.LoadLibrary(fp)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/usr/local/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libctesseract.so.1.0.0: cannot open shared object file: No such file or directory

# but specifying absolute path works...
>>> cdll.LoadLibrary('/usr/local/lib/libctesseract.so.1.0.1')
<CDLL '/usr/local/lib/libctesseract.so.1.0.1', handle 10fc530 at 7fcf71ab47d0>
>>> cdll.LoadLibrary('/usr/local/lib/libctesseract.so')
<CDLL '/usr/local/lib/libctesseract.so', handle 10fc530 at 7fcf71ab4710>
```

**Comment by clintharris** [comment]
Running via strace shows that `cdll.LoadLibrary('libctesseract.so')` searches the following directories (i.e.,  it doesn't include `/usr/local/lib/`, the directory where CTesseract's build puts the library):

```
open("/lib64/tls/x86_64/libctesseract.so.1.0.0", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/lib64/tls/libctesseract.so.1.0.0", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/lib64/x86_64/libctesseract.so.1.0.0", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/lib64/libctesseract.so.1.0.0", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/lib64/tls/x86_64/libctesseract.so.1.0.0", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/lib64/tls/libctesseract.so.1.0.0", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/lib64/x86_64/libctesseract.so.1.0.0", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/lib64/libctesseract.so.1.0.0", O_RDONLY) = -1 ENOENT (No such file or directory)
```

One work-around is to simply move the .so\* files to one of these directories.

Another option is to set the `LD_LIBRARY_PATH` env variable to `/usr/local/lib`.
